# Generated by Django 2.2.9 on 2022-05-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_groups_null_ondelete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
